"use client"
import Image from "next/image";
import styles from "./page.module.css";
import { useState } from "react";
import { FaHeart } from "react-icons/fa";


export default function Home() {
  const [inputEmail, setInputEmail] = useState("");
  const [verifEmail, setVerifEmail] = useState("");
  const [errorActive, setErrorActive] = useState(false);

  const regexp = /\[([^\]]+)\]/g;

  function check() {
    const result = [...inputEmail.matchAll(regexp)];
    if (result.length > 0) {
      const newResult = result.map((m) => m[1]);
      console.log(newResult);
      setVerifEmail(newResult.join(" - "));
      setErrorActive(true);
    }
  }

  return (
    <div className={styles.page}>
      <div className={styles.zoneNav}>
        <h1 className={styles.nomSite}>OkRecheck</h1>
        <a href="https://ko-fi.com/okrecheck_devnoai" className={styles.lienFooter}>  <button className={styles.boutonSupport}>
        <FaHeart className={styles.heart} color="red" size={28} style={{ marginRight: "8px" }} />
          <p className={styles.supportTitre}>Support the project</p>
        </button></a>
      </div>

      <div className={styles.zone_header}>
        <div className={styles.zone_titre_header}>
          <h1 className={styles.titreHeader}>
          Identify and fix careless mistakes in your emails or text generated by AI.
          </h1>
          <p className={styles.soustitreHeader}>
            Don’t let small mistakes harm a professional message: check it with one click.
          </p>
          <p className={styles.soustitreHeader}>
            MailShip automatically detects the elements you forgot to replace, such as:{" "}
            <span className={styles.spanError}>[Your first and last name], [Name of the institution]</span>.
          </p>
        </div>

        <textarea
          className={styles.inputmail}
          placeholder="Paste your AI-generated text here"
          onChange={(e) => setInputEmail(e.target.value)}
        />

        {errorActive && (
          <div className={styles.zoneErreur}>
            <h1 className={styles.titreErreur}>Detected items to replace:</h1>
            <p className={styles.listeErreur}>{verifEmail}</p>
          </div>
        )}

        <div className={styles.zoneBouton}>
          <button
            className={styles.boutonCorriger}
            onClick={() => {
              check();
              setErrorActive(true);
            }}
          >
            Checke
          </button>
        </div>
      </div>

      <div className={styles.zonefooter}>
      <a href="https://ko-fi.com/okrecheck_devnoai" className={styles.lienFooterkofi}>
      Liked it? Support 
        </a>
        <a href="/politique" className={styles.lienFooter}>
          Privacy Policy
        </a>
      </div>
    </div>
  );
}
